-- ONLINE RETAIL SALES DATABASE

-- STAGE 1: DATABASE CREATION

CREATE DATABASE retail_db;
USE retail_db;

-- STAGE 2: TABLE CREATION

CREATE TABLE CUSTOMERS(
CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(100),
EMAIL VARCHAR(100),
CITY VARCHAR(50)
);

CREATE TABLE PRODUCTS(
PRODUCT_ID INT PRIMARY KEY AUTO_INCREMENT,
PRODUCT_NAME VARCHAR(100),
PRICE DECIMAL(10,2)
);

CREATE TABLE ORDERS(
ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
CUSTOMER_ID INT,
ORDER_DATE DATE,
FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
); 

CREATE TABLE ORDER_ITEMS(
ORDER_ITEM_ID INT PRIMARY KEY AUTO_INCREMENT,
ORDER_ID INT,
PRODUCT_ID INT,
QUANTITY INT,
FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID),
FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);





