-- ONLINE RETAIL SALES DATABASE

-- STAGE 1: DATABASE CREATION

CREATE DATABASE retail_db;
USE retail_db;

-- STAGE 2: TABLE CREATION

CREATE TABLE CUSTOMERS(
CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(100),
EMAIL VARCHAR(100),
CITY VARCHAR(50)
);

CREATE TABLE PRODUCTS(
PRODUCT_ID INT PRIMARY KEY AUTO_INCREMENT,
PRODUCT_NAME VARCHAR(100),
PRICE DECIMAL(10,2)
);

CREATE TABLE ORDERS(
ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
CUSTOMER_ID INT,
ORDER_DATE DATE,
FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
); 

CREATE TABLE ORDER_ITEMS(
ORDER_ITEM_ID INT PRIMARY KEY AUTO_INCREMENT,
ORDER_ID INT,
PRODUCT_ID INT,
QUANTITY INT,
FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID),
FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

-- STAGE 3: INSERT DATA

-- INSERTING DATA INTO CUSTOMERS

INSERT INTO CUSTOMERS(NAME,EMAIL,CITY)
VALUES
('CHARITHA','CHARITHA@GMAIL.COM','HYDERABAD'),
('RAHUL','RAHUL@GMAIL.COM','DELHI'),
('SNEHA','SNEHA@GMAIL.COM','MUMBAI');

-- INSERTING DATA INTO PRODUCTS

INSERT INTO PRODUCTS(PRODUCT_NAME,PRICE)
VALUES
('LAPTOP',50000),
('PHONE',20000),
('HEADPHONES',2000),
('KEYBOARD',1500);

-- INSERTING DATA INTO ORDERS

INSERT INTO ORDERS(CUSTOMER_ID,ORDER_DATE)
VALUES
(1, '2025-03-01'),
(2, '2025-03-02'),
(1, '2025-03-05');

-- INSERTING DATA INTO ORDER_ITEMS

INSERT INTO ORDER_ITEMS (ORDER_ID,PRODUCT_ID,QUANTITY) 
VALUES
(1, 1, 1),
(1, 3, 2),
(2, 2, 1),
(3, 4, 3);











